import { useEffect, useRef, useState, type ChangeEvent } from 'react'
import QrScanner from 'qr-scanner'
import { Camera, Check, ImagePlus, QrCode, X } from 'lucide-react'

type Props = { onCheckIn: (token: string) => Promise<void>; onClose: () => void }
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
export function AttendanceScanner({ onCheckIn, onClose }: Props) {
  const videoRef=useRef<HTMLVideoElement>(null); const fileRef=useRef<HTMLInputElement>(null); const scannerRef=useRef<QrScanner|null>(null); const submittingRef=useRef(false)
  const [token,setToken]=useState(''); const [message,setMessage]=useState(''); const [pending,setPending]=useState(false); const [done,setDone]=useState(false); const [cameraOpen,setCameraOpen]=useState(false)
  useEffect(()=>()=>scannerRef.current?.destroy(),[])
  const submit=async(value=token)=>{const clean=value.trim(); if(!UUID.test(clean)){setMessage('Token QR không hợp lệ.');return} if(submittingRef.current)return; submittingRef.current=true;setPending(true);setMessage('');void scannerRef.current?.stop();try{await onCheckIn(clean);setDone(true);setMessage('Đã điểm danh thành công.')}catch(cause){setMessage(cause instanceof Error?cause.message:'Không thể điểm danh.')}finally{submittingRef.current=false;setPending(false)}}
  const startCamera=async()=>{if(!videoRef.current||pending)return;setMessage('');const scanner=new QrScanner(videoRef.current,(result)=>{setToken(result.data);void submit(result.data)},{preferredCamera:'environment',highlightScanRegion:true,highlightCodeOutline:true,returnDetailedScanResult:true});scannerRef.current?.destroy();scannerRef.current=scanner;try{await scanner.start();setCameraOpen(true);setMessage('Đưa QR vào khung camera rồi giữ máy ổn định.')}catch{setMessage('Không thể mở camera. Dùng nút CHỤP / CHỌN ẢNH bên dưới.')}}
  const scanPhoto=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setPending(true);setMessage('Đang đọc QR trong ảnh…');try{const result=await QrScanner.scanImage(file,{returnDetailedScanResult:true});setToken(result.data);await submit(result.data)}catch{setMessage('Không tìm thấy QR hợp lệ trong ảnh. Chụp gần hơn và thử lại.')}finally{setPending(false)}}
  return <section className="scanner-panel" role="dialog" aria-modal="true" aria-labelledby="scanner-title"><div className="scanner-panel__header"><div><p className="section-label">CONTRAST / CHECK IN</p><h2 id="scanner-title">QUÉT QR.</h2></div><button type="button" className="scanner-close" onClick={onClose} aria-label="Đóng scanner"><X/></button></div>{done?<div className="scanner-state scanner-state--success"><Check size={44}/><strong>ĐÃ CÓ MẶT.</strong></div>:<><div className={`scanner-view${cameraOpen?' is-active':''}`}><video ref={videoRef} className="scanner-video" muted playsInline/></div><div className="scanner-actions"><button type="button" className="button button--red" disabled={pending} onClick={startCamera}><Camera size={16}/> QUÉT CAMERA</button><button type="button" className="button button--dark" disabled={pending} onClick={()=>fileRef.current?.click()}><ImagePlus size={16}/> CHỤP / CHỌN ẢNH</button><input ref={fileRef} className="scanner-file-input" type="file" accept="image/*" capture="environment" onChange={scanPhoto}/></div><div className="manual-entry"><label htmlFor="attendance-code">HOẶC NHẬP TOKEN</label><div><input id="attendance-code" value={token} onChange={(event)=>setToken(event.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" autoComplete="off"/><button type="button" className="button button--dark" disabled={pending} onClick={()=>void submit()}>{pending?'ĐANG KIỂM TRA…':'ĐIỂM DANH'} <QrCode size={15}/></button></div></div></>}<p className="scanner-message" role={message&&!done?'alert':'status'}>{message}</p></section>
}
